version: '3.8'
services:
  backend:
    build: ./backend
    container_name: go-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: next-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    networks:
      - app-net

networks:
  app-net:
