FROM golang:1.25

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN go build -o app ./cmd/habit-tracker

ENV PATH="/go/bin:${PATH}"

EXPOSE 8080

# airインストール
RUN go install github.com/air-verse/air@latest

CMD ["air"]

